.TH MYSTRNCPY 3 "September 2026" "BSDSF24M059-OS-A01" "Library Functions"

.SH NAME
mystrncpy \- copy a specified number of characters

.SH SYNOPSIS
.B int mystrncpy(char* dest, const char* src, int n);

.SH DESCRIPTION
.B mystrncpy
copies up to
.I n
characters from the string pointed to by
.I src
to the destination buffer pointed to by
.I dest
and returns an integer status value.

.SH AUTHOR
Akmal kurovi.akmal@gmail.com