.TH MYSTRCAT 3 "September 2026" "BSDSF24M059-OS-A01" "Library Functions"

.SH NAME
mystrcat \- concatenate two strings

.SH SYNOPSIS
.B int mystrcat(char* dest, const char* src);

.SH DESCRIPTION
.B mystrcat
appends the string pointed to by
.I src
to the end of the string pointed to by
.I dest
and returns an integer status value.

.SH AUTHOR
Akmal